In [170]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

In [5]:
x = np.random.randint(2,10,5)
x

array([8, 4, 8, 6, 4])

In [6]:
np.min(x)

4

In [7]:
np.max(x)

8

In [9]:
np.argmax(x)

0

In [10]:
np.argmin(x)

1

In [11]:
x.ndim

1

In [12]:
x.size

5

In [13]:
len(x)

5

In [14]:
x.dtype

dtype('int64')

In [15]:
x.itemsize

8

In [18]:
np.sort(x)

array([4, 4, 6, 8, 8])

In [22]:
np.split(x, [2,2])

[array([8, 4]), array([], dtype=int64), array([8, 6, 4])]

In [23]:
a = np.random.randint(10, size = (2, 3)) 
b = np.random.randint(10, size = (2, 3))

In [24]:
a

array([[5, 9, 8],
       [3, 0, 5]])

In [25]:
b

array([[9, 2, 0],
       [7, 1, 7]])

In [27]:
a, b

(array([[5, 9, 8],
        [3, 0, 5]]),
 array([[9, 2, 0],
        [7, 1, 7]]))

In [30]:
np.concatenate((a,b), axis = 0)

array([[5, 9, 8],
       [3, 0, 5],
       [9, 2, 0],
       [7, 1, 7]])

In [32]:
np.concatenate((a,b), axis = 1)

array([[5, 9, 8, 9, 2, 0],
       [3, 0, 5, 7, 1, 7]])

In [34]:
np.split(x,[4])

[array([8, 4, 8, 6]), array([4])]

In [35]:
m = np.arange(20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
np.split(m, [1,3], axis = 0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [37]:
np.split(m, [1,3], axis = 1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [39]:
np.vsplit(m, [1, 3]) # verticle split dikey

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [40]:
upper, lower = np.vsplit(m, [3])

In [41]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [48]:
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [49]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [50]:
v

array([2, 1, 4, 3, 5])

In [51]:
v.sort()

In [52]:
v

array([1, 2, 3, 4, 5])

In [54]:
twoD = np.random.randint(5, 100, (3, 3))
twoD

array([[51, 15,  9],
       [72, 46, 29],
       [61, 51, 79]])

In [55]:
np.sort(twoD, axis = 0)

array([[51, 15,  9],
       [61, 46, 29],
       [72, 51, 79]])

In [56]:
np.sort(twoD, axis = 1)

array([[ 9, 15, 51],
       [29, 46, 72],
       [51, 61, 79]])

In [57]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [59]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

In [60]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d[1]

array([20, 25, 30])

In [62]:
arr_2d[1,1]

25

In [63]:
arr_2d[1:,2]

array([30, 45])

In [65]:
arr_2d[:1,:1]

array([[5]])

In [66]:
type(arr_2d[1,1])

numpy.int64

In [67]:
type(arr_2d[1][1])

numpy.int64

In [68]:
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [71]:
arr_2d[:,1]

array([10, 25, 40])

In [72]:
arr_2d[[0,2], 1:] 

array([[10, 15],
       [40, 45]])

In [73]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [77]:
arr_2d[2:,:2]

array([[35, 40]])

In [78]:
arr_2d[1,1] = 55
arr_2d

array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [80]:
arr_2d[1,1] = 55.5 # 55.5 became 55 because of int type.
arr_2d

array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [82]:
v = np.arange(0,30,3)

v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [84]:
v[[3,5,1,9]]

array([ 9, 15,  3, 27])

In [85]:
v[[1, 3, 7]]

array([ 3,  9, 21])

In [86]:
fancy1=v.reshape(2,5)
fancy1

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [88]:
arr2d = np.zeros((10, 10), dtype=int) 

arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [148]:
for x in range(arr2d.shape[0]):
    arr2d[x] = x
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [93]:
jj = np.arange(1,17).reshape(4,4)

jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [94]:
jj[2:,3]

array([12, 16])

In [96]:
jj[[1,2],[0,3]]

array([ 5, 12])

In [98]:
jj.sum()/len(jj)

34.0

In [99]:
np.mean(jj)

8.5

In [101]:
jj[[1,2,0],[0,3,1]]

array([ 5, 12,  2])

In [103]:
jj[[1,1],[1,3]]

array([6, 8])

In [104]:
jj[1,[1,3]]

array([6, 8])

In [105]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [106]:
jj[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [120]:
jj[1:3,[1,3]]

array([[ 6,  8],
       [10, 12]])

# Selection on a Condition

In [131]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [133]:
conditioan = arr > 4

In [134]:
arr[conditioan]

array([ 5,  6,  7,  8,  9, 10])

In [135]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [136]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
(arr !=3) & (arr!=4)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [139]:
arr[(arr<3) | (arr>8) & ((arr !=9) | (arr !=2))]

array([ 1,  2,  9, 10])

In [140]:
slice_of_arr = arr[0:6]

slice_of_arr

array([1, 2, 3, 4, 5, 6])

In [141]:
slice_of_arr[:] = 99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [142]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [143]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [146]:
arr_copy[:6] = [1,2,3,4,5,6]

In [147]:
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### ser = pd.Series(list("clarusway"))

ser

### ser.sort_index(ascending = True)

### ser.sort_values()

In [164]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [166]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [167]:
arr / arr

/var/folders/bv/8lk19kxx3_b_lty93f2n4v600000gn/T/ipykernel_910/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [168]:
import warnings
warnings.filterwarnings('ignore')

In [169]:
arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [171]:
1 / arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [172]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [173]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [174]:
np.subtract(arr,1)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [175]:
np.add(arr,2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [176]:
np.multiply(arr,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [177]:
np.power(arr,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [179]:
np.mod(arr,2)# making control of odd or even 

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [184]:
np.mod(arr[arr > 3],2) #take mod 2 for greater than 3

array([0, 1, 0, 1, 0, 1])

In [185]:
x1 = np.arange(9.0).reshape(3, 3)
x2 = np.arange(3.0)

In [186]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [187]:
x2

array([0., 1., 2.])

In [189]:
np.subtract(x1,x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [191]:
print(type(np.add))

<class 'numpy.ufunc'>


In [194]:
print(type(np.concatenate))

<class 'function'>


In [195]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [197]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [198]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [199]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [201]:
np.log10(1000)

3.0

In [202]:
v = np.array([1,1,2,2,3,3,3])


In [203]:
np.mean(v)

2.142857142857143

In [205]:
v.mean()

2.142857142857143

In [206]:
arry = np.array([4,7,1,9,1,2,6,8,10])

In [208]:
np.median(arry)

6.0

In [211]:
arry = np.sort(arry)

arry

array([ 1,  1,  2,  4,  6,  7,  8,  9, 10])

In [212]:
v.std()

0.8329931278350429

In [213]:
v.var()

0.6938775510204082

In [214]:
v.sum()

15

In [215]:
v.min()

1

In [217]:
np.ptp(v) # peak to peak

2

In [225]:
np.random.seed(42) #42 means that keep first entering (girdilerimiz)

In [226]:
xarr = np.random.randn(3,5)

xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783]])

In [227]:
np.mean(xarr)

0.010348524333336447

In [228]:
np.random.seed(42)
xarr = np.random.randn(3,5)

xarr


array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783]])