In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
a1 = np.array([1,2,3,4])
b1 = np.array([2,3,4,5])

In [4]:
np.sqrt(a1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [6]:
np.sqrt(a1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [8]:
my_tuple = 1,2,3,4,5

my_first_array = np.array(my_tuple)
my_first_array

array([1, 2, 3, 4, 5])

In [10]:
np.size(my_first_array)

5

In [11]:
my_first_array = np.append(my_first_array, (6,7))

In [12]:
my_first_array

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
listt = [1,2,3]

id(listt)

140615635127808

In [15]:
id(my_first_array)

140615636098960

In [16]:
my_first_array = np.append(my_first_array, (6,7,8,9))

In [18]:
id(my_first_array)

140615635262992

In [21]:
listt.append(4)

listt

[1, 2, 3, 4, 4]

In [22]:
id(listt)

140615635127808

In [23]:
a1.ndim

1

In [25]:
a=[1,2,3,4]
b=[2,3,4,5]
AsumB=[]
for i in range(len(a)):
    AsumB.append(a[i]+b[i])

AsumB

[3, 5, 7, 9]

In [28]:
a = np.array(a)
b = np.array(b)

In [29]:
a*b

array([ 2,  6, 12, 20])

In [49]:
np.full((2,3,3),7)

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

In [38]:
k = 5*"4"

In [39]:
k

'44444'

In [41]:
np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]])

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [50]:
import time
import sys

In [53]:
sys.getsizeof(5)

28

In [54]:
time.time()

1669459501.714883

In [55]:
start = time.time()
start

1669459524.820631

In [56]:
time.time() - start

22.98249077796936

In [65]:
size = 1000000
items1 = range(size)
items2 = range(size)
a1 = np.arange(size)
a2 = np.arange(size)
start = time.time()
result = [(x+y) for x, y in zip(items1, items2)]
print("python list took : ", (time.time() - start) * 1000)
start = time.time()
result = a1 + a2
print("numpy took :", (time.time()-start) * 1000)

python list took :  108.70194435119629
numpy took : 16.916990280151367
